-- =============================================================
-- Migration: 000010_create_sessions_notfications
-- JWT refresh tokens + in-app notification log
-- =============================================================
